"""Initial migration

Revision ID: 1d08ea3547f4
Revises: 
Create Date: 2025-12-09 16:46:24.468109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d08ea3547f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_first_name', sa.String(length=50), nullable=False),
    sa.Column('_last_name', sa.String(length=50), nullable=False),
    sa.Column('_email', sa.String(length=128), nullable=False),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('_is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_email')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_title', sa.String(length=100), nullable=False),
    sa.Column('_description', sa.String(length=1024), nullable=True),
    sa.Column('_price', sa.Float(), nullable=False),
    sa.Column('_latitude', sa.Float(), nullable=False),
    sa.Column('_longitude', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_amenity',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'amenity_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_text', sa.String(length=1024), nullable=False),
    sa.Column('_rating', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('place_amenity')
    op.drop_table('places')
    op.drop_table('users')
    op.drop_table('amenities')
    # ### end Alembic commands ###
